services:
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:29093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,CONTROLLER://0.0.0.0:29093,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      CLUSTER_ID: env-sensor-demo-cluster-1
      KAFKA_LOG_RETENTION_HOURS: 168
    networks:
      - shared

  nifi:
    image: apache/nifi:latest
    container_name: nifi
    ports:
      - "8443:8443"
    environment:
      - SINGLE_USER_CREDENTIALS_USERNAME=admin
      - SINGLE_USER_CREDENTIALS_PASSWORD=Password1234
    networks:
      - shared

  clickstack:
    image: clickhouse/clickstack-all-in-one:latest
    container_name: clickstack
    depends_on:
      - kafka
    ports:
      - "8123:8123"   
      - "9000:9000"   
      - "8080:8080"   
      - "4317:4317"
      - "4318:4318"
    environment:
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./config/config.xml:/etc/clickhouse-server/config.d/custom.xml
      - ./init:/init
    networks:
      - shared
    command: >
      bash -c "
      clickstack &
      until clickhouse-client --host ch-server --query='SELECT 1' >/dev/null 2>&1; do
        echo 'Waiting for ClickHouse...';
        sleep 2;
      done;
      echo 'Running init.sql...';
      cat /init/init.sql;
      clickhouse-client --host ch-server < /init/init.sql;
      echo 'Init done';
      wait
      "

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - clickstack
    networks:
      - shared

volumes:
  clickhouse_data:

networks:
  shared: